version: '2'
services:
  php:
    image: digbang/php-dev:7.0
    volumes:
     - ./docker/apache:/etc/apache2/sites-enabled:ro
     - .:/var/www/html
    ports:
     - "80:80"
    networks:
      appnet:
        ipv4_address: 172.18.0.20
  redis:
    image: redis:alpine
    networks:
     - appnet
  db:
    image: postgres:9.6
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: rft
      POSTGRES_DB: rft
      POSTGRES_USER: rft
    volumes:
     - data:/var/lib/postgresql/data
     - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
     - appnet
  smtp:
    image: mailhog/mailhog:latest
    ports:
     - "8025:8025"
    networks:
     - appnet
networks:
  appnet:
    driver: "bridge"
    ipam:
      driver: default
      config:
       - subnet: 172.18.0.0/16
volumes:
  data:
    driver: "local"
  search:
    driver: "local"
